# ================================
# errors.py
# ================================

INVALID_FILE_TYPE = "INVALID_FILE_TYPE"

FILE_TOO_LARGE = "FILE_TOO_LARGE"

FILE_CORRUPTED = "FILE_CORRUPTED"

EMPTY_FILE = "EMPTY_FILE"

PDF_CONVERSION_FAILED = "PDF_CONVERSION_FAILED"

AI_API_FAILED = "AI_API_FAILED"

AI_TIMEOUT = "AI_TIMEOUT"

INVALID_AI_RESPONSE = "INVALID_AI_RESPONSE"

EMPTY_EXTRACTION = "EMPTY_EXTRACTION"

RATE_LIMITED = "RATE_LIMITED"

INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"